TRUNCATE TABLE JOBS;

INSERT INTO JOBS 
(COMPLETED,  JOB_END_TIME, JOB_RUN_START_TIME, JOB_START_TIME, JOB_STATUS, JVM_NAME, LAST_UPDATED_TIME, LAST_UPDATED_USER, PARAMETERS, PROCESS_CODE_NAME, RECORD_CREATED_TIME, RECORD_CREATED_USER, STOP_FLAG, SUBMITTED_TIME)
VALUES 
(0.0,  CURRENT_TIMESTAMP,  DATEADD('SECOND',  -10,  CURRENT_TIMESTAMP),  DATEADD('SECOND',  -11,  CURRENT_TIMESTAMP),  'COMPLETED',  NULL,  
CURRENT_TIMESTAMP,  'MOVIE-APP',  NULL,  'PROCESS-FETCH-MOVIES',  DATEADD('SECOND',  -12,  CURRENT_TIMESTAMP),  'MOVIE-APP', 
NULL,  DATEADD('SECOND',  -13,  CURRENT_TIMESTAMP)); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -20, CURRENT_TIMESTAMP),  DATEADD('SECOND', -21, CURRENT_TIMESTAMP),  DATEADD('SECOND', -22, CURRENT_TIMESTAMP), DATEADD('SECOND', -23, CURRENT_TIMESTAMP),  
'COMPLETED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL);

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -30, CURRENT_TIMESTAMP),  DATEADD('SECOND', -31, CURRENT_TIMESTAMP),  DATEADD('SECOND', -32, CURRENT_TIMESTAMP), DATEADD('SECOND', -33, CURRENT_TIMESTAMP),  
'COMPLETED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL);  

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -40, CURRENT_TIMESTAMP),  DATEADD('SECOND', -41, CURRENT_TIMESTAMP),  DATEADD('SECOND', -42, CURRENT_TIMESTAMP), DATEADD('SECOND', -43, CURRENT_TIMESTAMP),  
'COMPLETED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -50, CURRENT_TIMESTAMP),  DATEADD('SECOND', -51, CURRENT_TIMESTAMP),  DATEADD('SECOND', -52, CURRENT_TIMESTAMP), DATEADD('SECOND', -53, CURRENT_TIMESTAMP),  
'COMPLETED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -60, CURRENT_TIMESTAMP),  DATEADD('SECOND', -61, CURRENT_TIMESTAMP),  DATEADD('SECOND', -62, CURRENT_TIMESTAMP), DATEADD('SECOND', -63, CURRENT_TIMESTAMP),  
'COMPLETED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -70, CURRENT_TIMESTAMP),  DATEADD('SECOND', -71, CURRENT_TIMESTAMP),  DATEADD('SECOND', -72, CURRENT_TIMESTAMP), DATEADD('SECOND', -73, CURRENT_TIMESTAMP),  
'COMPLETED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -80, CURRENT_TIMESTAMP),  DATEADD('SECOND', -81, CURRENT_TIMESTAMP),  DATEADD('SECOND', -82, CURRENT_TIMESTAMP), DATEADD('SECOND', -83, CURRENT_TIMESTAMP),  
'COMPLETED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -90, CURRENT_TIMESTAMP),  DATEADD('SECOND', -91, CURRENT_TIMESTAMP),  DATEADD('SECOND', -92, CURRENT_TIMESTAMP), DATEADD('SECOND', -93, CURRENT_TIMESTAMP),  
'COMPLETED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 


INSERT INTO JOBS 
(COMPLETED,  JOB_END_TIME, JOB_RUN_START_TIME, JOB_START_TIME, JOB_STATUS, JVM_NAME, LAST_UPDATED_TIME, LAST_UPDATED_USER, PARAMETERS, PROCESS_CODE_NAME, RECORD_CREATED_TIME, RECORD_CREATED_USER, STOP_FLAG, SUBMITTED_TIME)
VALUES 
(0.0,  CURRENT_TIMESTAMP,  DATEADD('SECOND',  -10,  CURRENT_TIMESTAMP),  DATEADD('SECOND',  -11,  CURRENT_TIMESTAMP),  'FAILED',  NULL,  
CURRENT_TIMESTAMP,  'MOVIE-APP',  NULL,  'PROCESS-FETCH-MOVIES',  DATEADD('SECOND',  -12,  CURRENT_TIMESTAMP),  'MOVIE-APP', 
NULL,  DATEADD('SECOND',  -13,  CURRENT_TIMESTAMP)); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -20, CURRENT_TIMESTAMP),  DATEADD('SECOND', -21, CURRENT_TIMESTAMP),  DATEADD('SECOND', -22, CURRENT_TIMESTAMP), DATEADD('SECOND', -23, CURRENT_TIMESTAMP),  
'FAILED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL);

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -30, CURRENT_TIMESTAMP),  DATEADD('SECOND', -31, CURRENT_TIMESTAMP),  DATEADD('SECOND', -32, CURRENT_TIMESTAMP), DATEADD('SECOND', -33, CURRENT_TIMESTAMP),  
'FAILED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL);  

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -40, CURRENT_TIMESTAMP),  DATEADD('SECOND', -41, CURRENT_TIMESTAMP),  DATEADD('SECOND', -42, CURRENT_TIMESTAMP), DATEADD('SECOND', -43, CURRENT_TIMESTAMP),  
'FAILED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -50, CURRENT_TIMESTAMP),  DATEADD('SECOND', -51, CURRENT_TIMESTAMP),  DATEADD('SECOND', -52, CURRENT_TIMESTAMP), DATEADD('SECOND', -53, CURRENT_TIMESTAMP),  
'FAILED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -60, CURRENT_TIMESTAMP),  DATEADD('SECOND', -61, CURRENT_TIMESTAMP),  DATEADD('SECOND', -62, CURRENT_TIMESTAMP), DATEADD('SECOND', -63, CURRENT_TIMESTAMP),  
'FAILED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -70, CURRENT_TIMESTAMP),  DATEADD('SECOND', -71, CURRENT_TIMESTAMP),  DATEADD('SECOND', -72, CURRENT_TIMESTAMP), DATEADD('SECOND', -73, CURRENT_TIMESTAMP),  
'FAILED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -80, CURRENT_TIMESTAMP),  DATEADD('SECOND', -81, CURRENT_TIMESTAMP),  DATEADD('SECOND', -82, CURRENT_TIMESTAMP), DATEADD('SECOND', -83, CURRENT_TIMESTAMP),  
'FAILED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -90, CURRENT_TIMESTAMP),  DATEADD('SECOND', -91, CURRENT_TIMESTAMP),  DATEADD('SECOND', -92, CURRENT_TIMESTAMP), DATEADD('SECOND', -93, CURRENT_TIMESTAMP),  
'FAILED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(COMPLETED,  JOB_END_TIME, JOB_RUN_START_TIME, JOB_START_TIME, JOB_STATUS, JVM_NAME, LAST_UPDATED_TIME, LAST_UPDATED_USER, PARAMETERS, PROCESS_CODE_NAME, RECORD_CREATED_TIME, RECORD_CREATED_USER, STOP_FLAG, SUBMITTED_TIME)
VALUES 
(0.0,  CURRENT_TIMESTAMP,  DATEADD('SECOND',  -10,  CURRENT_TIMESTAMP),  DATEADD('SECOND',  -11,  CURRENT_TIMESTAMP),  'IN PROGRESS',  NULL,  
CURRENT_TIMESTAMP,  'MOVIE-APP',  NULL,  'PROCESS-FETCH-MOVIES',  DATEADD('SECOND',  -12,  CURRENT_TIMESTAMP),  'MOVIE-APP', 
NULL,  DATEADD('SECOND',  -13,  CURRENT_TIMESTAMP)); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -20, CURRENT_TIMESTAMP),  DATEADD('SECOND', -21, CURRENT_TIMESTAMP),  DATEADD('SECOND', -22, CURRENT_TIMESTAMP), DATEADD('SECOND', -23, CURRENT_TIMESTAMP),  
'IN PROGRESS',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL);

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -30, CURRENT_TIMESTAMP),  DATEADD('SECOND', -31, CURRENT_TIMESTAMP),  DATEADD('SECOND', -32, CURRENT_TIMESTAMP), DATEADD('SECOND', -33, CURRENT_TIMESTAMP),  
'IN PROGRESS',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL);  

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -40, CURRENT_TIMESTAMP),  DATEADD('SECOND', -41, CURRENT_TIMESTAMP),  DATEADD('SECOND', -42, CURRENT_TIMESTAMP), DATEADD('SECOND', -43, CURRENT_TIMESTAMP),  
'IN PROGRESS',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -50, CURRENT_TIMESTAMP),  DATEADD('SECOND', -51, CURRENT_TIMESTAMP),  DATEADD('SECOND', -52, CURRENT_TIMESTAMP), DATEADD('SECOND', -53, CURRENT_TIMESTAMP),  
'IN PROGRESS',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -60, CURRENT_TIMESTAMP),  DATEADD('SECOND', -61, CURRENT_TIMESTAMP),  DATEADD('SECOND', -62, CURRENT_TIMESTAMP), DATEADD('SECOND', -63, CURRENT_TIMESTAMP),  
'IN PROGRESS',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -70, CURRENT_TIMESTAMP),  DATEADD('SECOND', -71, CURRENT_TIMESTAMP),  DATEADD('SECOND', -72, CURRENT_TIMESTAMP), DATEADD('SECOND', -73, CURRENT_TIMESTAMP),  
'IN PROGRESS',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -80, CURRENT_TIMESTAMP),  DATEADD('SECOND', -81, CURRENT_TIMESTAMP),  DATEADD('SECOND', -82, CURRENT_TIMESTAMP), DATEADD('SECOND', -83, CURRENT_TIMESTAMP),  
'IN PROGRESS',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -90, CURRENT_TIMESTAMP),  DATEADD('SECOND', -91, CURRENT_TIMESTAMP),  DATEADD('SECOND', -92, CURRENT_TIMESTAMP), DATEADD('SECOND', -93, CURRENT_TIMESTAMP),  
'IN PROGRESS',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(COMPLETED,  JOB_END_TIME, JOB_RUN_START_TIME, JOB_START_TIME, JOB_STATUS, JVM_NAME, LAST_UPDATED_TIME, LAST_UPDATED_USER, PARAMETERS, PROCESS_CODE_NAME, RECORD_CREATED_TIME, RECORD_CREATED_USER, STOP_FLAG, SUBMITTED_TIME)
VALUES 
(0.0,  CURRENT_TIMESTAMP,  DATEADD('SECOND',  -10,  CURRENT_TIMESTAMP),  DATEADD('SECOND',  -11,  CURRENT_TIMESTAMP),  'ABORTED',  NULL,  
CURRENT_TIMESTAMP,  'MOVIE-APP',  NULL,  'PROCESS-FETCH-MOVIES',  DATEADD('SECOND',  -12,  CURRENT_TIMESTAMP),  'MOVIE-APP', 
NULL,  DATEADD('SECOND',  -13,  CURRENT_TIMESTAMP)); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -20, CURRENT_TIMESTAMP),  DATEADD('SECOND', -21, CURRENT_TIMESTAMP),  DATEADD('SECOND', -22, CURRENT_TIMESTAMP), DATEADD('SECOND', -23, CURRENT_TIMESTAMP),  
'ABORTED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL);

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -30, CURRENT_TIMESTAMP),  DATEADD('SECOND', -31, CURRENT_TIMESTAMP),  DATEADD('SECOND', -32, CURRENT_TIMESTAMP), DATEADD('SECOND', -33, CURRENT_TIMESTAMP),  
'ABORTED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL);  

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -40, CURRENT_TIMESTAMP),  DATEADD('SECOND', -41, CURRENT_TIMESTAMP),  DATEADD('SECOND', -42, CURRENT_TIMESTAMP), DATEADD('SECOND', -43, CURRENT_TIMESTAMP),  
'ABORTED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -50, CURRENT_TIMESTAMP),  DATEADD('SECOND', -51, CURRENT_TIMESTAMP),  DATEADD('SECOND', -52, CURRENT_TIMESTAMP), DATEADD('SECOND', -53, CURRENT_TIMESTAMP),  
'ABORTED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -60, CURRENT_TIMESTAMP),  DATEADD('SECOND', -61, CURRENT_TIMESTAMP),  DATEADD('SECOND', -62, CURRENT_TIMESTAMP), DATEADD('SECOND', -63, CURRENT_TIMESTAMP),  
'ABORTED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -70, CURRENT_TIMESTAMP),  DATEADD('SECOND', -71, CURRENT_TIMESTAMP),  DATEADD('SECOND', -72, CURRENT_TIMESTAMP), DATEADD('SECOND', -73, CURRENT_TIMESTAMP),  
'ABORTED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -80, CURRENT_TIMESTAMP),  DATEADD('SECOND', -81, CURRENT_TIMESTAMP),  DATEADD('SECOND', -82, CURRENT_TIMESTAMP), DATEADD('SECOND', -83, CURRENT_TIMESTAMP),  
'ABORTED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

INSERT INTO JOBS 
(JOB_RUN_START_TIME, JOB_START_TIME, JOB_END_TIME, SUBMITTED_TIME, JOB_STATUS, RECORD_CREATED_USER, LAST_UPDATED_USER, PROCESS_CODE_NAME, COMPLETED, JVM_NAME, LAST_UPDATED_TIME, PARAMETERS, RECORD_CREATED_TIME, STOP_FLAG)
VALUES 
(DATEADD('SECOND',  -90, CURRENT_TIMESTAMP),  DATEADD('SECOND', -91, CURRENT_TIMESTAMP),  DATEADD('SECOND', -92, CURRENT_TIMESTAMP), DATEADD('SECOND', -93, CURRENT_TIMESTAMP),  
'ABORTED',  'MOVIE-APP',  'MOVIE-APP',  'PROCESS-FETCH-MOVIES', 0.0,  NULL, CURRENT_TIMESTAMP, NULL,  CURRENT_TIMESTAMP,  NULL); 

COMMIT;